appVersion: apps/v1beta
kind: Deployment
metadata:
  name: raedar-deployment
spec:
  selector:
    matchLabels:
      app: raedar
  replicas: 1
  template:
    metadata:
      labels:
        app: raedar
    spec:
      containers:
      - name: raedar
        image: raedar:1.0
        ports:
        - containerPort: 8080
      env:
      - name:  ENVVARNAME
        value:  ENVVARVALUE
