version: '3.7'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: raedar_dev
      POSTGRES_USER: raedar_admin
      POSTGRES_PASSWORD: krs1krs1
      # DATABASE_HOST: 5432
    ports:
      - '5555:5432'
    volumes:
      - dbdata_test:/var/lib/postgresql/data
    networks:
      - back_test
  redis_test:
    image: redis:alpine
    networks:
      - back_test
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: raedar_backend
    environment:
      DB_NAME: raedar_dev
      DB_USER: raedar_admin
      DB_PASSWORD: krs1krs1
      DB_PORT: 5555
    labels: 
      - "com.example.description=Raedar App"
      - "com.example.department=Raedar Software"
      - "com.example.label-with-empty-value="
    networks:
      - back_test
    ports:
      - 8080:8080 
    volumes:
      # This is go modules cache, without it you will have to
      # re-download all dependencies after restarting container
      - go_modules_test:/go/pkg/mod/cache
      - ./:/code:cached
    working_dir: /backend
    depends_on:
      - postgres_test
      - redis_test

volumes:
  go-go_modules_test:
  dbdata_test:

networks:
  back_test:
    driver: bridge
