version: '3'

services:
  db:
    container_name: raedar_db
    image: postgres
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: raedar_api
      POSTGRES_PASSWORD: krs1krs1
    ports:
      - 5432:5432

  app:
    image: raedar/backend:v1.0
    ports:
      - 8000:8080
    volumes:
      # This is go modules cache, without it you will have to
      # re-download all dependencies after restarting container
      - modules:/go/pkg/mod/cache
      - ./:/code:cached
    working_dir: /backend
    depends_on: db

  volumes:
    modules:
      driver: local
    
  raedarapi:
    container_name: raedar_api
    image: fahdjamy/raedarapi:v1
    hostname: raedarapi
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      GET_HOST_FROM: dns
    networks:
      - raedarnet
    volumes:
      - .:/go/backend/raedarAPI
    ports: 
      - 8080:8080
    depends_on:
      - db
    links:
      - db
    labels:
      kompose.service.type: loadBalancer

  networks: 
    raedarnet:
      driver: brigde
