name: BuildTestAndMerge

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    name: TestApp
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: raedar_test
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Check out code
        uses: actions/checkout@v1

      - name: set environment variables
        uses: allenevans/set-env@v1.0.0
        with:
          MODE: TESTING
          TEST_DB_HOST: 127.0.0.1
          SENDER_EMAIL_ADDRESS: ${{ secrets.SENDER_EMAIL_ADDRESS }}
          SENDER_EMAIL_PASSWORD: ${{ secrets.SENDER_EMAIL_PASSWORD }}
          TEST_DB_USER: postgres
          TEST_DB_PASSWORD: postgres
          TEST_DB_NAME: raedar_test
          TEST_DB_PORT: 5432
      - uses: actions/checkout@v2
      - name: Test app
        env:
          MODE: TESTING
          TEST_DB_HOST: 127.0.0.1
          TEST_DB_USER: postgres
          TEST_DB_PASSWORD: postgres
          TEST_DB_NAME: raedar_test
          TEST_DB_PORT: 5432
          SENDER_EMAIL_ADDRESS: ${{ secrets.SENDER_EMAIL_ADDRESS }}
          SENDER_EMAIL_PASSWORD: ${{ secrets.SENDER_EMAIL_PASSWORD }}
        run: go test -v -cover ./...
